#mongo+mongo-express
version: "3.8"
name: mongodbnew
networks:
  mongodb_network:
    driver: bridge

volumes:
  mdb:
    name: mdb
  mdbcfg:
    name: mdbcfg

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mdb:/data/db
      - mdbcfg:/data/configdb
    enviroment:
      - MONGO_INITDB_ROOT_USERNAME: rootuser
      - MONGO_INITDB_ROOT_PASSWORD: rootpass 
    networks:
      - mongodb_network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
     networks:
      - mongodb_network
